### ISSUE TITLE
Fix Release Build Action

### ISSUE THREAD

**Issue by pysan3** [erg-lang/erg-language-server#3]
Hi, author of #2 here.

I am happy to see that the lsp is being improved over time.
However, it seems that the releases created by github actions are failing from v0.1.6.

The neovim setup automatically tries to update the version by pulling such files as `els-x86_64-unknown-linux-gnu.tar.gz` from the releases. So, updates for the current two versions seem to fail with the current situation.

Unfortunately I lack knowledge on GH Actions and rust cross platform compiling, so may I ask you to fix this problem?

Thank you in advance,
pysan3

**Comment by mtshiba** [comment]
Since Erg 0.5.10 introduced the std library, we seem to get permission denied on some targets when creating directories.
I have removed the target where the build fails, but I wonder if there is any way to give the proper permission.

**Comment by pysan3** [comment]
Hmm...
I also looked into the actions but could find anything suspicious.
Maybe this could be related? https://github.com/rust-lang/cargo/issues/6757

Currently the [neovim setup](https://github.com/williamboman/mason.nvim/blob/8f9bf0e4e4d946fe76961dea8f46a250be7e2686/lua/mason-registry/erg-language-server/init.lua#L17) relies on all the builds to be successful, so should I make an issue there so that the setup falls back to `cargo install` if the OS build is not found or something?

**Comment by mtshiba** [comment]
This issue has been solved since `els` has been integrated into `erg`.
